[workspace]
members = [
  "fugue",
  "fugue-arch",
  "fugue-bytes",
  "fugue-bv",
  "fugue-core",
  "fugue-core-derive",
  "fugue-core-idalib",
  "fugue-lifter",
  "fugue-lifter-aarch64",
  "fugue-lifter-arm",
  "fugue-lifter-codegen",
  "fugue-lifter-mips",
  "fugue-lifter-packager",
  "fugue-lifter-runtime",
  "fugue-lifter-x86",
  "fugue-python",
  "fugue-specs",
  "fugue-sleigh",
  "fugue-sleigh-language",
  "fugue-sleigh-marshal",
  "fugue-sleigh-semantics",
]
resolver = "2"

[workspace.lints.rust]
mismatched_lifetime_syntaxes = "allow"

[profile.bench]
debug = true
