[package]
name = "fugue-lifter-runtime"
version = "0.3.0"
edition = "2021"

[features]
bincode = ["dep:bincode"]
serde = ["dep:serde"]
default = []

[dependencies]
arrayvec = "0.7"
bincode = { version = "2", features = ["derive"], optional = true }
itertools = "0.14"
phf = { version = "0.11", features = ["macros"] }
serde = { version = "1", features = ["derive"], optional = true }
thiserror = "2"
