mod analysis;
mod artefact;
mod dominance;
mod error;
mod form;
mod generate;
mod graph;
mod id;
mod pool;
mod rewrite;
mod span;
pub(crate) mod verify;

pub use analysis::{IlAnalyser, IlAnalysis};
pub use artefact::{ControlFlowIl, IlArtefact, IlMetadata, IlSchemaVersion, PersistableIl};
pub use dominance::{IlDominance, IlDominanceFrontier};
pub use error::IlError;
pub use form::{DialectId, IlFormId, IlFormIdError};
pub use generate::{IlConverter, IlGenerationContext, IlGenerationError, IlProducer, IlSubject};
pub use graph::{IlBlock, IlBlockPredecessors, IlBlockProperties, IlEdgeKinds, IlGraph};
pub(crate) use id::il_id;
pub use id::{IlBlockId, IlExprId, IlOpId, IlValueId};
pub use pool::IlIndexRange;
pub(crate) use pool::{IlCsr, IlPool};
pub use rewrite::IlRewrite;
pub use span::{IlParentSpan, IlSourceSpan};
pub use verify::{StructureError, StructureVerifierError};
