[package]
name = "fugue-lifter-packager"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "lifter-packager"
path = "src/main.rs"

[features]
default = ["build", "sync"]
build = [
    "dep:fugue-lifter-codegen",
    "dep:fugue-lifter-runtime",
    "dep:fugue-sleighc",
    "dep:rkyv",
    "dep:tempfile",
]
sync = ["dep:tempfile"]

[dependencies]
clap = "4"
flate2 = "1"
fugue-lifter-codegen = { version = "0.3", path = "../fugue-lifter-codegen", optional = true }
fugue-lifter-runtime = { version = "0.3", path = "../fugue-lifter-runtime", optional = true }
fugue-sleighc = { version = "0.3", optional = true }
rkyv = { version = "0.8", features = ["arrayvec-0_7"], optional = true }
tempfile = { version = "3", optional = true }
thiserror = "2"

[lints]
workspace = true
