use super::NonReturningExterns;
use crate::registry;

static POSIX_NON_RETURNING: &[&str] = &[
    "abort",
    "exit",
    "_exit",
    "_Exit",
    "cexit",
    "_cexit",
    "c_exit",
    "_c_exit",
    "xexit",
    "_xexit",
    "quick_exit",
    "pthread_exit",
    "reboot",
    "longjmp",
    "_longjmp",
    "__longjmp",
    "siglongjmp",
    "longjmp_chk",
    "__longjmp_chk",
    "assert_fail",
    "__assert_fail",
    "__assert_perror_fail",
    "assert_rtn",
    "__assert_rtn",
    "__assert",
    "chk_fail",
    "__chk_fail",
    "fortify_fail",
    "__fortify_fail",
    "stack_chk_fail",
    "__stack_chk_fail",
    "__stack_chk_fail_local",
    "err",
    "errx",
    "verr",
    "verrx",
    "error_at_line",
    "__libc_fatal",
    "cxa_throw",
    "__cxa_throw",
    "cxa_rethrow",
    "__cxa_rethrow",
    "cxa_bad_cast",
    "__cxa_bad_cast",
    "cxa_call_unexpected",
    "__cxa_call_unexpected",
    "cxa_terminate",
    "__cxa_terminate",
    "Unwind_Resume",
    "_Unwind_Resume",
    "ZSt9terminatev",
    "_ZSt9terminatev",
    "ZSt10unexpectedv",
    "_ZSt10unexpectedv",
    "ZN10__cxxabiv111__terminateEPFvvE",
    "_ZN10__cxxabiv111__terminateEPFvvE",
];

registry::submit! {
    NonReturningExterns::new("posix-non-returning", POSIX_NON_RETURNING)
}
