[package]
name = "fugue-lifter-ppc"
version = "0.3.0"
edition = "2024"
build = "build.rs"

[features]
ppc-be = []
ppc-le = []
ppc64-be = []
ppc64-le = []
bundled = ["fugue-lifter-packager"]
compiled = ["fugue-lifter-codegen", "fugue-lifter-codegen/bundled-compiler"]
default = ["ppc-be", "ppc-le", "ppc64-be", "ppc64-le", "bundled"]

[dependencies]
fugue-lifter-runtime = { version = "0.3", path = "../fugue-lifter-runtime" }

[build-dependencies]
fugue-lifter-codegen = { version = "0.3", path = "../fugue-lifter-codegen", default-features = false, optional = true }
fugue-lifter-packager = { version = "0.3", path = "../fugue-lifter-packager", default-features = false, optional = true }

[lints]
workspace = true
