[package]
name = "fugue-lifter-ppc"
version = "0.3.0"
edition = "2024"
build = "build.rs"

[features]
ppc-be = []
ppc-le = []
ppc64-be = []
ppc64-le = []
ppc64-a2alt-be = []
ppc64-a2alt-le = []
bundled = ["fugue-lifter-packager"]
compiled = ["fugue-lifter-codegen", "fugue-lifter-codegen/bundled-compiler"]
default = [
  "bundled",
  "ppc-be",
  "ppc-le",
  "ppc64-a2alt-be",
  "ppc64-a2alt-le",
  "ppc64-be",
  "ppc64-le",
]

[dependencies]
fugue-lifter-runtime = { version = "0.3", path = "../fugue-lifter-runtime" }

[build-dependencies]
fugue-lifter-codegen = { version = "0.3", path = "../fugue-lifter-codegen", default-features = false, optional = true }
fugue-lifter-packager = { version = "0.3", path = "../fugue-lifter-packager", default-features = false, optional = true }

[lints]
workspace = true
