[package]
name = "fugue-lifter-arm"
version = "0.3.0"
edition = "2021"
build = "build.rs"

[features]
arm-be = []
arm-le = []
bundled = ["fugue-lifter-packager"]
compiled = ["fugue-lifter-codegen", "fugue-lifter-codegen/bundled-compiler"]
default = ["arm-be", "arm-le", "bundled"]

[dependencies]
fugue-lifter-runtime = { version = "0.3", path = "../fugue-lifter-runtime" }

[build-dependencies]
fugue-lifter-codegen = { version = "0.3", path = "../fugue-lifter-codegen", default-features = false, optional = true }
fugue-lifter-packager = { version = "0.3", path = "../fugue-lifter-packager", optional = true }

[lints]
workspace = true
