[package]
name = "fugue-core-idalib"
version = "0.3.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2021"

[dependencies]
fallible-iterator = "0.3"
fugue-core = { version = "0.3", path = "../fugue-core" }
idalib = "0.6"
thiserror = "2"
tracing = "0.1"

[build-dependencies]
idalib-build = "0.6"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[lints]
workspace = true
