[package]
name = "fugue-core-idalib"
version = "0.3.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2021"

[dependencies]
fallible-iterator = "0.3"
fugue-base = { version = "0.3", path = "../fugue-base" }
idalib = { version = "0.5", git = "ssh://git@github.com/binarly-io/idalib.git", branch = "feature/processor-metadata-apis" }
thiserror = "1"

[build-dependencies]
idalib-build = { version = "0.5", git = "ssh://git@github.com/binarly-io/idalib.git", branch = "feature/processor-metadata-apis" }
