[package]
name = "fugue-lifter-codegen"
version = "0.3.0"
edition = "2021"

[features]
bundled-compiler = ["fugue-sleighc"]
default = ["bundled-compiler"]

[dependencies]
anyhow = "1"
diffy = "0.5"
fugue-sleighc = { version = "0.3", optional = true }
fugue-sleigh-language = { path = "../fugue-sleigh-language" }
heck = "0.5"
indexmap = "2.12"
itertools = "0.14"
proc-macro2 = "1"
quote = "1"
thiserror = "2"
walkdir = "2"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
