[package]
name = "fugue-core"
version = "0.3.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2024"

[features]
default = ["static-lifters"]
static-lifters = [
  "fugue-lifter/arm",
  "fugue-lifter/aarch64",
  "fugue-lifter/mips",
  "fugue-lifter/x86",
  "fugue-lifter/x86-64",
  "fugue-lifter/bundled",
]
mdbx = ["libmdbx"]
rocksdb = ["dep:rocksdb"]
sqlite = ["r2d2", "r2d2_sqlite", "rusqlite"]

[dependencies]
anyhow = "1"
arrayvec = "0.7"
bitflags = "2"
bytes = "1"
clone_dyn = "0.55"
crossbeam-skiplist = "0.1"
dashmap = "6.1"
digest = "0.10"
downcast-rs = "2"
fallible-iterator = "0.3"
fixedbitset = "0.5"
flume = "0.12"
fugue-bv = { version = "0.3", path = "../fugue-bv" }
fugue-bytes = { version = "0.3", path = "../fugue-bytes" }
fugue-core-derive = { version = "0.3", path = "../fugue-core-derive" }
fugue-lifter = { version = "0.3", path = "../fugue-lifter", default-features = false }
fugue-sleigh-language = { version = "0.3", path = "../fugue-sleigh-language" }
fugue-specs = { version = "0.3", path = "../fugue-specs", features = ["rkyv"] }
hex-display = "0.3"
indexmap = "2"
inventory = "0.3"
iset = { git = "https://github.com/fugue-re/fugue-iset", branch = "feature/inclusive-intervals", package = "fugue-iset", features = ["rkyv"] }
itertools = "0.14"
libmdbx = { version = "0.6", optional = true }
md-5 = "0.10"
memmap2 = "0.9"
object = "0.39"
ouroboros = "0.18"
parking_lot = { version = "0.12", features = ["arc_lock"] }
quick_cache = "0.6"
r2d2 = { version = "0.8", optional = true }
r2d2_sqlite = { version = "0.32", optional = true }
rangemap = "1.7"
range-set-blaze = { version = "0.6", features = ["rog_experimental"] }
rayon = "1"
rkyv = { version = "0.8", features = ["arrayvec-0_7", "smallvec-1"] }
rocksdb = { version = "0.24", features = ["serde1", "snappy"], optional = true }
rusqlite = { version = "0.38", features = ["bundled"], optional = true }
rustc-hash = "2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.16"
serde-yaml = { version = "0.0.12", package = "serde-saphyr" }
sha2 = "0.10"
smallvec = "1.15"
smol_str = "0.3"
thiserror = "2"
tinyset = { version = "0.5", package = "fugue-tinyset", features = ["rkyv"] }
tracing = "0.1"
typeid = "1"
uuid = { version = "1", features = ["serde", "v7"] }
ustr = { version = "1.1", package = "fugue-ustr", features = ["rkyv", "serde"] }
walkdir = "2.5"
yaxpeax-arch = { version = "0.3", default-features = false }
yaxpeax-arm = { version = "0.4", git = "https://github.com/fugue-re/yaxpeax-arm.git", rev = "e34ced89551c607befc6dfc3186e2f6af9c77a10" }
yaxpeax-x86 = "2.0"
zip = { version = "7", default-features = false, features = ["zstd"] }

[dev-dependencies]
tempfile = "3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[[bench]]
name = "analysis_engine"
harness = false
required-features = ["static-lifters"]

[[bench]]
name = "entity_storage"
harness = false

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["md-5"]
