[package]
name = "fugue-core"
version = "0.3.0"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2024"

[features]
mdbx = ["libmdbx"]
sqlite = ["r2d2", "r2d2_sqlite", "rusqlite"]
rocksdb = ["dep:rocksdb"]
default = ["sqlite"]

[dependencies]
anyhow = "1"
arrayvec = "0.7"
bitflags = "2"
bytes = "1"
clone_dyn = "0.55"
dashmap = "6.1"
digest = "0.10"
downcast-rs = "2"
fallible-iterator = "0.3"
fugue-bytes = { version = "0.3", path = "../fugue-bytes" }
fugue-core-derive = { version = "0.3", path = "../fugue-core-derive" }
fugue-lifter = { version = "0.3", path = "../fugue-lifter", features = ["rkyv"] }
fugue-specs = { version = "0.3", path = "../fugue-specs", features = ["rkyv"] }
hex-display = "0.3"
indexmap = "2.12"
inventory = "0.3"
iset = { version = "0.3", package = "fugue-iset", features = ["rkyv"] }
itertools = "0.14"
libmdbx = { version = "0.6", optional = true }
md-5 = "0.10"
memmap2 = "0.9"
object = "0.38"
ouroboros = "0.18"
quick_cache = "0.6"
parking_lot = "0.12"
r2d2 = { version = "0.8", optional = true }
r2d2_sqlite = { version = "0.32", optional = true }
range-set-blaze = "0.4"
rkyv = { version = "0.8", features = ["arrayvec-0_7", "smallvec-1"] }
rocksdb = { version = "0.24", features = ["serde1", "snappy"], optional = true }
rusqlite = { version = "0.38", features = ["bundled"], optional = true }
rustc-hash = "2.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.16"
serde-yaml = { version = "0.0.12", package = "serde-saphyr" }
sha2 = "0.10"
skiplist = "0.6"
smallvec = "1.15"
thiserror = "2"
tinyset = { version = "0.5", package = "fugue-tinyset", features = ["rkyv"] }
tracing = "0.1"
typeid = "1"
uuid = { version = "1", features = ["serde", "v7"] }
ustr = { version = "1.1", package = "fugue-ustr", features = ["rkyv", "serde"] }
walkdir = "2.5"
yaxpeax-arch = { version = "0.3", default-features = false }
yaxpeax-arm = "0.4"
yaxpeax-x86 = "2.0"
zip = { version = "7", default-features = false, features = ["zstd"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = ["md-5"]
